### ISSUE TITLE
ability to turn off npc jobs

### ISSUE THREAD

**Issue by Alokas123** [esx-framework/esx_mechanicjob#12]
can sombody add feature that you can turn off npc jobs on config

**Comment by alvwashere** [comment]
Check the fork on my profile let me know if that helps.

**I have not tested this simply just added an if statement to the command that contains the function to start an NPC job and its keymapping as well as added the config**

**Comment by thesysadmindev** [comment]
I've included this in PR #15.

**Comment by Gellipapa** [comment]
#15 If fixed, after can close this issue.

**Comment by thesysadmindev** [comment]
Requested changes have been implemented (apologies for the delay), pending review from @Gellipapa.

**Comment by Gellipapa** [comment]
Close #15 and close this issue.
