### ISSUE TITLE
Repairkit doesn't pick planes, helicopters and boats.

### ISSUE THREAD

**Issue by AdvancedLua** [esx-framework/esx_mechanicjob#20]
When I tried to repair a boat, plane or helicopter it doens't let me do it. I had a look to the script and changed the following thing:

On line 629 from:
`GetClosestVehicle(coords.x, coords.y, coords.z, 5.0, 0, 71)`

to

`vehicle = ESX.Game.GetClosestVehicle(coords)`

After changing this it picked the boat, plane and helicopter, hopefully you guys can do something with this issue!

**Comment by Gellipapa** [comment]
Hi! Exactly, the basic native 71 ID will not handle the boat or the plane so yes ESX has to use the closest vehicle method to work. Thanks for the bug report.

**Comment by Gellipapa** [comment]
Hi! @AdvancedLua I fixed your problem thank you for report problem.
