### ISSUE TITLE
 mission NPC key

### ISSUE THREAD

**Issue by S-F-L** [esx-framework/esx_mechanicjob#21]
I can't change the F6 for NPC missions. because it is canceled every time I arrive next to the vehicle since it is the same button to cancel the mission and put it on the flatbed

I tried to put another letter "I" for example and it didn't work

**Comment by Gellipapa** [comment]
@S-F-L Hi! I fixed your problem you can set controls in config.lua. Sometimes RegisterKeyMapping cached, you should delete your server cache or you can change key in gta 5 settings -> key bindings -> fivem.
