### ISSUE TITLE
How can i make map blip less size

### ISSUE THREAD

**Issue by TMarcccci** [esx-framework/esx_mechanicjob#71]
How can i make map blip less size?

**Comment by larscrazynl** [comment]
Almost at the bottom of config.lua:

change:
Size = { x = 1.5, y = 1.5, z = 1.0 },
to:
Size = { x = 1.0, y = 1.0, z = 1.0 },

**Comment by fantomeus** [comment]
not work... :/

**Comment by AgenChicken24** [comment]
Go on line 818 and change the number 
![Annotation 2020-07-14 051821](https://user-images.githubusercontent.com/64702468/87372987-76115a80-c591-11ea-9bb6-33aa8e041e98.png)
